repos:
    - repo: local
      hooks:
          - id: prettier-pre-commit
            name: Prettier format
            entry: bash ./scripts/pre-commit-formatter
            language: system
            verbose: true
