repos:
    - repo: local
      hooks:
          - id: prettier-pre-commit
            name: Prettier format
            entry: bash ./scripts/prettier-pre-commit
            language: system
            verbose: true
